### PR TITLE
Added support for more mods and finished outpost objects

### PR DESCRIPTION
**Pull request by thakyZ**
I finished adding support for More Outpost Objects.
I also fixed an issue with two of the patch files for the Outpost Wall Locker as their file names were spelled wrong.
Added support for Neko Alternate, Arcana, The Ironsides, and Letheia Expanded.
I have yet to test all of them, but I can guarantee that it should work out of the box, if anything some things may have been spelled wrong but won't cause any errors.

### CODE REVIEW

**Comment by Kherae** [comment]
prefer that you test it yourself fully if possible. if nothing else, make sure you put everything through a linter

**Comment by thakyZ** [comment]
I can test this tomorrow as I have a test in the morning and I need to study then sleep.

**Comment by Kherae** [comment]
you've a lot more work ahead of ya, since neo's added support for some mods like more outpost objects. might wanna compare

**Comment by Kherae** [comment]
https://github.com/NeoVanAlemania/EnhancedStorage

**Comment by thakyZ** [comment]
Okay, I can do so, I have been without a computer for some time. So It'll need to be put off for now.

**Pull request closed without merging**
